const REVEAL_INTERVAL_MS = 500;
const HOLD_AFTER_LAST_MS = 600;
const API = import.meta.env.VITE_API_URL;
const MAX_ROUNDS = 9;
const GRID_SIZE = 9;
const STARTING_LENGTH = 3;

export { REVEAL_INTERVAL_MS, HOLD_AFTER_LAST_MS, API, MAX_ROUNDS, GRID_SIZE, STARTING_LENGTH };
